name: scraperenv
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip:
    - news-please
    - unidecode
  - jupyter=1.0.0
  - pandas=0.23.4
  - python=3.7.3
  - numpy==1.16.3
  - configparser
  - requests
  - ipykernel=5.1.3
  - jupyterlab